language: cpp
sudo: required
dist: xenial

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
- eval "${MATRIX_EVAL}"
- ./scripts/install_cmake-3.9.sh

install:
- ./scripts/install_opencv-3.4.1.sh

build:
- mkdir build/ && cd build/
- cmake ..
- make -j4


